// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBwjVEAmBnzdR7ClvWW_1Xwsubyc_XCmA',
    appId: '1:414677289354:web:331d91ffc993de37672073',
    messagingSenderId: '414677289354',
    projectId: 'beatflow-bb182',
    authDomain: 'beatflow-bb182.firebaseapp.com',
    storageBucket: 'beatflow-bb182.firebasestorage.app',
    measurementId: 'G-PSQY3KHNW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR-cAoCksljLWrkEWbMDHTjYpUaDtHWMg',
    appId: '1:414677289354:android:dc79100d6f6e1ef8672073',
    messagingSenderId: '414677289354',
    projectId: 'beatflow-bb182',
    storageBucket: 'beatflow-bb182.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKep44Dj_6pP69O139AnGsYXWM1pFtGig',
    appId: '1:414677289354:ios:b1efa3b99eafb58b672073',
    messagingSenderId: '414677289354',
    projectId: 'beatflow-bb182',
    storageBucket: 'beatflow-bb182.firebasestorage.app',
    iosBundleId: 'com.example.newPro',
  );
}
